version: "3.8"

services:
  
  spark-master:
    build: .
    container_name: spark-master
    command: >
      bash -c "
      /opt/spark/sbin/start-master.sh &&
      tail -f /opt/spark/logs/*"
    ports:
      - "7077:7077"
      - "8080:8080"
    volumes:
      - ./:/app

  spark-worker-1:
    build: .
    container_name: spark-worker-1
    command: >
      bash -c "
      /opt/spark/sbin/start-worker.sh spark://spark-master:7077 &&
      tail -f /opt/spark/logs/*"
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    volumes:
      - ./:/app

  spark-worker-2:
    build: .
    container_name: spark-worker-2
    command: >
      bash -c "
      /opt/spark/sbin/start-worker.sh spark://spark-master:7077 &&
      tail -f /opt/spark/logs/*"
    depends_on:
      - spark-master
    ports:
      - "8082:8081"
    volumes:
      - ./:/app

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: warehouse
      POSTGRES_USER: spark
      POSTGRES_PASSWORD: spark
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  airflow-webserver:
    image: apache/airflow:2.8.1
    container_name: airflow-webserver
    depends_on:
      - postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: SequentialExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://spark:spark@postgres/warehouse
    volumes:
      - ./:/opt/airflow
    ports:
      - "8085:8080" 
    command: webserver

  airflow-scheduler:
    image: apache/airflow:2.8.1
    container_name: airflow-scheduler
    depends_on:
      - airflow-webserver
    environment:
      AIRFLOW__CORE__EXECUTOR: SequentialExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://spark:spark@postgres/warehouse
    volumes:
      - ./:/opt/airflow
    command: scheduler

volumes:
  postgres_data:


